version: "3"
services:
  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pgpassword
      - POSTGRES_DB=dbdumb
    ports:
      - "5432:5432"
    volumes:
      - ./internal/postgres/schema.sql:/docker-entrypoint-initdb.d/init.sql
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - ./internal/mysql/schema.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dbdumb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
  pgadmin:
    image: "thajeztah/pgadmin4:latest"
    ports:
      - "5050:5050"