version: "3"
services:
  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pgpassword
      - POSTGRES_DB=dbdumb
    ports:
      - "5432:5432"
    volumes:
      - ./internal/postgres/schema.sql:/docker-entrypoint-initdb.d/init.sql
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - ./internal/mysql/schema.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dbdumb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
  oracle:
    image: registry.gitlab.com/joshraphael/img/oracle/database:11.2.0.1-xe
    shm_size: '1gb'
    ports:
      - 1521:1521
    environment:
      - ORACLE_PWD=password11
    volumes:
      - ./internal/oracle/schema.sql:/u01/app/oracle/scripts/startup/schema.sql
  pgadmin:
    image: "thajeztah/pgadmin4:latest"
    ports:
      - "5050:5050"
  dbdumb:
    build: .
    depends_on:
      - postgres
      - mysql
      - oracle
    command: bash scripts/test.sh